### ISSUE TITLE
cf-redis-example app is broken

### ISSUE THREAD

**Issue by BalaSubramanian-L** [pivotal-cf/cf-redis-example-app#6] opened 2018-01-31 19:18 UTC
The app is broken cause Sinatra (1.4.7) uses deprecated Fixnum. 

logs:

2018-01-31T13:55:37.552-05:00 [API/0] [OUT] Created app with guid 96b6e233-f997-41d1-83bc-b41ef981425b
2018-01-31T13:55:37.934-05:00 [API/0] [OUT] Updated app with guid 96b6e233-f997-41d1-83bc-b41ef981425b ({"route"=>"4d440a45-8ede-4564-97fb-fe0a99d2951b", :verb=>"add", :relation=>"routes", :related_guid=>"4d440a45-8ede-4564-97fb-fe0a99d2951b"})
2018-01-31T14:14:56.587-05:00 [API/0] [OUT] Updated app with guid 96b6e233-f997-41d1-83bc-b41ef981425b ({"name"=>"smoke-test", "memory"=>256, "stack_guid"=>"ebf0a125-7e98-4e2c-b0fa-cb956dc1f2ae"})
2018-01-31T14:15:02.974-05:00 [API/0] [OUT] Updated app with guid 96b6e233-f997-41d1-83bc-b41ef981425b ({"state"=>"STARTED"})
2018-01-31T14:15:02.996-05:00 [STG/0] [OUT] Downloading binary_buildpack...
2018-01-31T14:15:02.996-05:00 [STG/0] [OUT] Downloading staticfile_buildpack...
2018-01-31T14:15:02.996-05:00 [STG/0] [OUT] Downloading hwc_buildpack...
2018-01-31T14:15:02.996-05:00 [STG/0] [OUT] Downloading ruby_buildpack...
2018-01-31T14:15:03.001-05:00 [STG/0] [OUT] Downloading nodejs_buildpack...
2018-01-31T14:15:03.035-05:00 [STG/0] [OUT] Downloaded binary_buildpack
2018-01-31T14:15:03.035-05:00 [STG/0] [OUT] Downloading python_buildpack...
2018-01-31T14:15:03.035-05:00 [STG/0] [OUT] Downloaded staticfile_buildpack
2018-01-31T14:15:03.035-05:00 [STG/0] [OUT] Downloading go_buildpack...
2018-01-31T14:15:03.036-05:00 [STG/0] [OUT] Downloaded ruby_buildpack
2018-01-31T14:15:03.036-05:00 [STG/0] [OUT] Downloading php_buildpack...
2018-01-31T14:15:03.036-05:00 [STG/0] [OUT] Downloaded nodejs_buildpack
2018-01-31T14:15:03.036-05:00 [STG/0] [OUT] Downloading java_buildpack_offline...
2018-01-31T14:15:03.036-05:00 [STG/0] [OUT] Downloaded hwc_buildpack
2018-01-31T14:15:03.037-05:00 [STG/0] [OUT] Downloading dotnet_core_buildpack...
2018-01-31T14:15:03.063-05:00 [STG/0] [OUT] Downloaded php_buildpack
2018-01-31T14:15:03.064-05:00 [STG/0] [OUT] Downloaded python_buildpack
2018-01-31T14:15:03.065-05:00 [STG/0] [OUT] Downloaded java_buildpack_offline
2018-01-31T14:15:03.066-05:00 [STG/0] [OUT] Creating container
2018-01-31T14:15:03.066-05:00 [STG/0] [OUT] Downloaded dotnet_core_buildpack
2018-01-31T14:15:03.066-05:00 [STG/0] [OUT] Downloaded go_buildpack
2018-01-31T14:15:03.391-05:00 [STG/0] [OUT] Successfully created container
2018-01-31T14:15:03.392-05:00 [STG/0] [OUT] Downloading app package...
2018-01-31T14:15:03.486-05:00 [STG/0] [OUT] Staging...
2018-01-31T14:15:03.486-05:00 [STG/0] [OUT] Downloaded app package (1.9M)
2018-01-31T14:15:04.662-05:00 [STG/0] [OUT] -----> Ruby Buildpack version 1.7.5
2018-01-31T14:15:04.664-05:00 [STG/0] [OUT] -----> Supplying Ruby
2018-01-31T14:15:04.680-05:00 [STG/0] [OUT] Copy [/tmp/buildpacks/8dc9f7021d8c27287edd1a2ab0fada1b/dependencies/530b8129893066f29b08db0722619964/bundler-1.15.4-e083af6d.tgz]
2018-01-31T14:15:04.680-05:00 [STG/0] [OUT] -----> Installing bundler 1.15.4
2018-01-31T14:15:05.312-05:00 [STG/0] [OUT] [31;1m**WARNING**[0m You have not declared a Ruby version in your Gemfile.
2018-01-31T14:15:05.312-05:00 [STG/0] [OUT] Defaulting to 2.4.2
2018-01-31T14:15:05.312-05:00 [STG/0] [OUT] See http://docs.cloudfoundry.org/buildpacks/ruby/index.html#runtime for more information.
2018-01-31T14:15:05.312-05:00 [STG/0] [OUT] Copy [/tmp/buildpacks/8dc9f7021d8c27287edd1a2ab0fada1b/dependencies/d0c4ac4b660f6af04a81ed79fc1b18b2/ruby-2.4.2-linux-x64-3810a760.tgz]
2018-01-31T14:15:05.312-05:00 [STG/0] [OUT] -----> Installing ruby 2.4.2
2018-01-31T14:15:07.670-05:00 [STG/0] [OUT] as well as configured git local gems, and other settings that should
2018-01-31T14:15:07.670-05:00 [STG/0] [OUT] [31;1m**WARNING**[0m You have the `.bundle/config` file checked into your repository
2018-01-31T14:15:07.670-05:00 [STG/0] [OUT] It contains local state like the location of the installed bundle
2018-01-31T14:15:07.670-05:00 [STG/0] [OUT] not be shared between multiple checkouts of a single repo. Please
2018-01-31T14:15:07.670-05:00 [STG/0] [OUT] remove the `.bundle/` folder from your repo and add it to your `.gitignore` file.
2018-01-31T14:15:08.464-05:00 [STG/0] [OUT] Running: bundle install --without development:test --jobs=4 --retry=4 --path /tmp/app/.cloudfoundry/0/vendor_bundle --binstubs /tmp/app/.cloudfoundry/0/binstubs --deployment
2018-01-31T14:15:08.464-05:00 [STG/0] [OUT] -----> Installing dependencies using bundler 1.15.4
2018-01-31T14:15:09.301-05:00 [STG/0] [OUT] Using bundler 1.15.4
2018-01-31T14:15:09.307-05:00 [STG/0] [OUT] Using cf-app-utils 0.6 from http://github.com/cloudfoundry/cf-app-utils-ruby.git (at /tmp/app815382597/app/vendor/cache/cf-app-utils-ruby-bbad1b0df516@bbad1b0)
2018-01-31T14:15:09.308-05:00 [STG/0] [OUT] Installing rack 1.6.4
2018-01-31T14:15:09.312-05:00 [STG/0] [OUT] Installing redis 3.3.3
2018-01-31T14:15:09.319-05:00 [STG/0] [OUT] Installing tilt 2.0.2
2018-01-31T14:15:09.814-05:00 [STG/0] [OUT] Installing rack-protection 1.5.3
2018-01-31T14:15:09.865-05:00 [STG/0] [OUT] Installing sinatra 1.4.7
2018-01-31T14:15:10.064-05:00 [STG/0] [OUT] Bundle complete! 6 Gemfile dependencies, 7 gems now installed.
2018-01-31T14:15:10.066-05:00 [STG/0] [OUT] Gems in the groups development and test were not installed.
2018-01-31T14:15:10.068-05:00 [STG/0] [OUT] Bundled gems are installed into /tmp/app/.cloudfoundry/0/vendor_bundle.
2018-01-31T14:15:10.070-05:00 [STG/0] [OUT] Cleaning up the bundler cache.
2018-01-31T14:15:11.227-05:00 [STG/0] [OUT] -----> Creating runtime environment
2018-01-31T14:15:11.450-05:00 [STG/0] [OUT] -----> Saving vendor_bundle to cache
2018-01-31T14:15:11.946-05:00 [STG/0] [OUT] -----> Finalizing Ruby
2018-01-31T14:15:12.520-05:00 [STG/0] [OUT] -----> Copy binaries to app/bin directory
2018-01-31T14:15:18.745-05:00 [STG/0] [OUT] Exit status 0
2018-01-31T14:15:18.746-05:00 [STG/0] [OUT] Uploading droplet...
2018-01-31T14:15:18.746-05:00 [STG/0] [OUT] Staging complete
2018-01-31T14:15:18.746-05:00 [STG/0] [OUT] Uploading droplet, build artifacts cache...
2018-01-31T14:15:18.746-05:00 [STG/0] [OUT] Uploading build artifacts cache...
2018-01-31T14:15:18.864-05:00 [STG/0] [OUT] Uploaded build artifacts cache (1.4M)
2018-01-31T14:15:25.486-05:00 [STG/0] [OUT] Uploaded droplet (21.5M)
2018-01-31T14:15:25.490-05:00 [STG/0] [OUT] Uploading complete
2018-01-31T14:15:25.521-05:00 [STG/0] [OUT] Destroying container
2018-01-31T14:15:25.724-05:00 [CELL/0] [OUT] Creating container
2018-01-31T14:15:26.054-05:00 [CELL/0] [OUT] Successfully created container
2018-01-31T14:15:26.140-05:00 [STG/0] [OUT] Successfully destroyed container
2018-01-31T14:15:27.972-05:00 [CELL/0] [OUT] Starting health monitoring of container
2018-01-31T14:15:29.184-05:00 [APP/PROC/WEB/0] [ERR] /home/vcap/app/.cloudfoundry/0/vendor_bundle/ruby/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1226: warning: constant ::Fixnum is deprecated
2018-01-31T14:15:29.219-05:00 [APP/PROC/WEB/0] [ERR] /home/vcap/app/.cloudfoundry/0/vendor_bundle/ruby/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1226: warning: constant ::Fixnum is deprecated
2018-01-31T14:15:29.221-05:00 [APP/PROC/WEB/0] [ERR] /home/vcap/app/.cloudfoundry/0/vendor_bundle/ruby/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1226: warning: constant ::Fixnum is deprecated
2018-01-31T14:15:29.222-05:00 [APP/PROC/WEB/0] [ERR] /home/vcap/app/.cloudfoundry/0/vendor_bundle/ruby/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1226: warning: constant ::Fixnum is deprecated
2018-01-31T14:15:29.403-05:00 [APP/PROC/WEB/0] [ERR] [2018-01-31 19:15:29] INFO ruby 2.4.2 (2017-09-14) [x86_64-linux]
2018-01-31T14:15:29.403-05:00 [APP/PROC/WEB/0] [ERR] [2018-01-31 19:15:29] INFO WEBrick 1.3.1
2018-01-31T14:15:29.406-05:00 [APP/PROC/WEB/0] [ERR] [2018-01-31 19:15:29] INFO WEBrick::HTTPServer#start: pid=13 port=8080
2018-01-31T14:15:30.079-05:00 [CELL/0] [OUT] Container became healthy

**Comment by mariantalla** [comment] 2018-02-05 17:00
Hi @BalaSubramanian-L - thanks for raising this.

Do you mind sharing the commands that you used to push the app?

Updating the sinatra version will probably fix the issue, but I'm curious as I can't reproduce it locally.

**Comment by BalaSubramanian-L** [comment] 2018-02-05 17:57
cf push smoke-test -m 256M -p "C:\Devops\work\GIT\redis-smoketest\cf-redis-smoke-tests\assets\cf-smoketest-app" -s cflinuxfs2

 i have cloned the app repo in my local

**Comment by mariantalla** [comment] 2018-02-06 16:06
Hey @BalaSubramanian-L - could you please pull the latest master ([a63f06a5e3dcbeac17d131c830969ffa37ba383d](https://github.com/pivotal-cf/cf-redis-example-app/commit/a63f06a5e3dcbeac17d131c830969ffa37ba383d) and let me know if it fixed the warning messages you got?

This commit updates the app's Gemfile to use the lastest stable sinatra, 2.0.0.

**Comment by BalaSubramanian-L** [comment] 2018-02-06 17:26
Hi @mariantalla the app is running now , it does show few info errors on WEBrick 1.3.1 and ruby 2.4.2

but in order for my smoke test to work in my pcf  setup i need the submodule in https://github.com/pivotal-cf/cf-redis-smoke-tests/tree/master/assets to use those changes.

Second, smoke-test instance for redis deployment should download this new version of cf-redis-smoke-tests

2018-02-06T11:36:48.525-05:00 [API/0] [OUT] Created app with guid 1ac0932d-fa73-4263-9c73-46b98da4e7bf
2018-02-06T11:36:48.943-05:00 [API/0] [OUT] Updated app with guid 1ac0932d-fa73-4263-9c73-46b98da4e7bf ({"route"=>"04b9f7fd-d1fa-4935-9a0a-2c390a246c76", :verb=>"add", :relation=>"routes", :related_guid=>"04b9f7fd-d1fa-4935-9a0a-2c390a246c76"})
2018-02-06T11:36:55.287-05:00 [API/0] [OUT] Updated app with guid 1ac0932d-fa73-4263-9c73-46b98da4e7bf ({"state"=>"STARTED"})
2018-02-06T11:36:55.316-05:00 [STG/0] [OUT] Downloading binary_buildpack...
2018-02-06T11:36:55.317-05:00 [STG/0] [OUT] Downloading python_buildpack...
2018-02-06T11:36:55.317-05:00 [STG/0] [OUT] Downloading hwc_buildpack...
2018-02-06T11:36:55.318-05:00 [STG/0] [OUT] Downloading java_buildpack_offline...
2018-02-06T11:36:55.325-05:00 [STG/0] [OUT] Downloading ruby_buildpack...
2018-02-06T11:36:55.351-05:00 [STG/0] [OUT] Downloaded binary_buildpack
2018-02-06T11:36:55.351-05:00 [STG/0] [OUT] Downloading nodejs_buildpack...
2018-02-06T11:36:55.352-05:00 [STG/0] [OUT] Downloading staticfile_buildpack...
2018-02-06T11:36:55.352-05:00 [STG/0] [OUT] Downloaded java_buildpack_offline
2018-02-06T11:36:55.352-05:00 [STG/0] [OUT] Downloading go_buildpack...
2018-02-06T11:36:55.352-05:00 [STG/0] [OUT] Downloaded ruby_buildpack
2018-02-06T11:36:55.353-05:00 [STG/0] [OUT] Downloading php_buildpack...
2018-02-06T11:36:55.353-05:00 [STG/0] [OUT] Downloaded hwc_buildpack
2018-02-06T11:36:55.353-05:00 [STG/0] [OUT] Downloaded python_buildpack
2018-02-06T11:36:55.353-05:00 [STG/0] [OUT] Downloading dotnet_core_buildpack...
2018-02-06T11:36:55.381-05:00 [STG/0] [OUT] Downloaded go_buildpack
2018-02-06T11:36:55.381-05:00 [STG/0] [OUT] Downloaded php_buildpack
2018-02-06T11:36:55.381-05:00 [STG/0] [OUT] Downloaded nodejs_buildpack
2018-02-06T11:36:55.381-05:00 [STG/0] [OUT] Downloaded staticfile_buildpack
2018-02-06T11:36:55.382-05:00 [STG/0] [OUT] Downloaded dotnet_core_buildpack
2018-02-06T11:36:55.382-05:00 [STG/0] [OUT] Creating container
2018-02-06T11:36:55.859-05:00 [STG/0] [OUT] Successfully created container
2018-02-06T11:36:55.860-05:00 [STG/0] [OUT] Downloading app package...
2018-02-06T11:36:55.995-05:00 [STG/0] [OUT] Downloaded app package (2M)
2018-02-06T11:36:55.995-05:00 [STG/0] [OUT] Staging...
2018-02-06T11:36:57.552-05:00 [STG/0] [OUT] -----> Ruby Buildpack version 1.7.5
2018-02-06T11:36:57.554-05:00 [STG/0] [OUT] -----> Supplying Ruby
2018-02-06T11:36:57.578-05:00 [STG/0] [OUT] Copy [/tmp/buildpacks/8dc9f7021d8c27287edd1a2ab0fada1b/dependencies/530b8129893066f29b08db0722619964/bundler-1.15.4-e083af6d.tgz]
2018-02-06T11:36:57.578-05:00 [STG/0] [OUT] -----> Installing bundler 1.15.4
2018-02-06T11:36:58.499-05:00 [STG/0] [OUT] [31;1m**WARNING**[0m You have not declared a Ruby version in your Gemfile.
2018-02-06T11:36:58.499-05:00 [STG/0] [OUT] -----> Installing ruby 2.4.2
2018-02-06T11:36:58.499-05:00 [STG/0] [OUT] See http://docs.cloudfoundry.org/buildpacks/ruby/index.html#runtime for more information.
2018-02-06T11:36:58.499-05:00 [STG/0] [OUT] Defaulting to 2.4.2
2018-02-06T11:36:58.500-05:00 [STG/0] [OUT] Copy [/tmp/buildpacks/8dc9f7021d8c27287edd1a2ab0fada1b/dependencies/d0c4ac4b660f6af04a81ed79fc1b18b2/ruby-2.4.2-linux-x64-3810a760.tgz]
2018-02-06T11:37:01.848-05:00 [STG/0] [OUT] [31;1m**WARNING**[0m You have the `.bundle/config` file checked into your repository
2018-02-06T11:37:01.848-05:00 [STG/0] [OUT] remove the `.bundle/` folder from your repo and add it to your `.gitignore` file.
2018-02-06T11:37:01.848-05:00 [STG/0] [OUT] It contains local state like the location of the installed bundle
2018-02-06T11:37:01.848-05:00 [STG/0] [OUT] as well as configured git local gems, and other settings that should
2018-02-06T11:37:01.848-05:00 [STG/0] [OUT] not be shared between multiple checkouts of a single repo. Please
2018-02-06T11:37:03.043-05:00 [STG/0] [OUT] -----> Installing dependencies using bundler 1.15.4
2018-02-06T11:37:03.043-05:00 [STG/0] [OUT] Running: bundle install --without development:test --jobs=4 --retry=4 --path /tmp/app/.cloudfoundry/0/vendor_bundle --binstubs /tmp/app/.cloudfoundry/0/binstubs --deployment
2018-02-06T11:37:03.688-05:00 [STG/0] [OUT] Warning: the running version of Bundler (1.15.4) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
2018-02-06T11:37:04.240-05:00 [STG/0] [OUT] Using bundler 1.15.4
2018-02-06T11:37:04.249-05:00 [STG/0] [OUT] Using cf-app-utils 0.6 from http://github.com/cloudfoundry/cf-app-utils-ruby.git (at /tmp/app809074708/app/vendor/cache/cf-app-utils-ruby-bbad1b0df516@bbad1b0)
2018-02-06T11:37:04.249-05:00 [STG/0] [OUT] Installing rack 2.0.4
2018-02-06T11:37:04.249-05:00 [STG/0] [OUT] Installing mustermann 1.0.1
2018-02-06T11:37:04.253-05:00 [STG/0] [OUT] Installing redis 3.3.3
2018-02-06T11:37:04.523-05:00 [STG/0] [OUT] Installing tilt 2.0.8
2018-02-06T11:37:05.106-05:00 [STG/0] [OUT] Installing rack-protection 2.0.0
2018-02-06T11:37:05.160-05:00 [STG/0] [OUT] Installing sinatra 2.0.0
2018-02-06T11:37:05.267-05:00 [STG/0] [OUT] Bundle complete! 6 Gemfile dependencies, 8 gems now installed.
2018-02-06T11:37:05.271-05:00 [STG/0] [OUT] Gems in the groups development and test were not installed.
2018-02-06T11:37:05.274-05:00 [STG/0] [OUT] Bundled gems are installed into /tmp/app/.cloudfoundry/0/vendor_bundle.
2018-02-06T11:37:05.278-05:00 [STG/0] [OUT] Cleaning up the bundler cache.
2018-02-06T11:37:05.909-05:00 [STG/0] [OUT] Warning: the running version of Bundler (1.15.4) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
2018-02-06T11:37:06.509-05:00 [STG/0] [OUT] -----> Creating runtime environment
2018-02-06T11:37:06.776-05:00 [STG/0] [OUT] -----> Saving vendor_bundle to cache
2018-02-06T11:37:07.457-05:00 [STG/0] [OUT] -----> Finalizing Ruby
2018-02-06T11:37:08.295-05:00 [STG/0] [OUT] -----> Copy binaries to app/bin directory
2018-02-06T11:37:16.920-05:00 [STG/0] [OUT] Uploading droplet, build artifacts cache...
2018-02-06T11:37:16.920-05:00 [STG/0] [OUT] Staging complete
2018-02-06T11:37:16.920-05:00 [STG/0] [OUT] Exit status 0
2018-02-06T11:37:16.921-05:00 [STG/0] [OUT] Uploading build artifacts cache...
2018-02-06T11:37:16.921-05:00 [STG/0] [OUT] Uploading droplet...
2018-02-06T11:37:17.042-05:00 [STG/0] [OUT] Uploaded build artifacts cache (1.5M)
2018-02-06T11:37:20.800-05:00 [STG/0] [OUT] Uploaded droplet (21.7M)
2018-02-06T11:37:20.809-05:00 [STG/0] [OUT] Uploading complete
2018-02-06T11:37:20.842-05:00 [STG/0] [OUT] Destroying container
2018-02-06T11:37:21.064-05:00 [CELL/0] [OUT] Creating container
2018-02-06T11:37:21.688-05:00 [STG/0] [OUT] Successfully destroyed container
2018-02-06T11:37:21.729-05:00 [CELL/0] [OUT] Successfully created container
2018-02-06T11:37:24.377-05:00 [CELL/0] [OUT] Starting health monitoring of container
2018-02-06T11:37:26.443-05:00 [APP/PROC/WEB/0] [ERR] [2018-02-06 16:37:26] INFO WEBrick 1.3.1
2018-02-06T11:37:26.443-05:00 [APP/PROC/WEB/0] [ERR] [2018-02-06 16:37:26] INFO ruby 2.4.2 (2017-09-14) [x86_64-linux]
2018-02-06T11:37:26.444-05:00 [APP/PROC/WEB/0] [ERR] [2018-02-06 16:37:26] INFO WEBrick::HTTPServer#start: pid=14 port=8080
2018-02-06T11:37:26.512-05:00 [CELL/0] [OUT] Container became healthy

**Comment by mariantalla** [comment] 2018-02-07 11:14
Thanks @BalaSubramanian-L - we've update the smoke tests repo, good catch.

Is there anything related to the cf-redis-example-app not working? If not, are you happy for me to close this issue?

cc @dark5un

**Comment by BalaSubramanian-L** [comment] 2018-02-07 15:25
Hey  @mariantalla i have submitted a new support ticket to pivotal and they decided to create a hotfix on redis-service-adapters , so for the cf-redis-example-app, i guess it should be ok to close now as my app starts fine now. 

I will open another request if need in the future

**Comment by mariantalla** [comment] 2018-02-07 16:14
Sounds good, thanks.

**Closed by mariantalla** 2018-02-07 16:14 UTC
